# Project information
site_name: Emily Lasko's Data Science and Programming Portfolio
site_url: https://enl9076.github.io/
site_author: Emily Lasko, PhD
site_description: >-
  TBD

# Configuration:
theme:
  name: windmill-dark
  color_mode: 'dark'
  user_color_mode_toggle: true