# Project information
site_name: Emily Lasko's Data Science and Programming Portfolio
site_url: https://enl9076.github.io/
site_author: Emily Lasko, PhD
site_description: >-
  TBD

# Configuration:
theme:
  name: material
  color_mode: 'dark'
  user_color_mode_toggle: true

# Page tree
nav:
- Home: index.md
- Current projects:
  - "Fish Tank Auto Top-Off System with Companion App"
  - "Random Fact Generator App"

- Previous data science projects:
  - ""

- Previous python projects:
  - "Password Manager"
  - "PC Monitoring Tool" : "pc_monitoring_tool/readme.md"

- Previous arduino projects:
  - "Weather lamp"